### ISSUE TITLE
No new-helper installed

### ISSUE THREAD

**Issue by magicaltrevor** [gmr/helper#1]
Tried following the documentation, got helper installed new-helper not found anywhere. Please advise.

**Comment by frol** [comment]
@gmr The question was about `new-helper` command that is described as a second step in the project documentation example: http://helper.readthedocs.io/en/latest/example.html

**Comment by frol** [comment]
And the exact problem is that there is no such command when you install `helper`:

```
$ virtualenv ./env
$ . ./env/bin/activate
$ pip install helper
$ new-helper -h
file: Unknown command 'new-helper'
$ which new-helper
which: no new-helper in (/tmp/env/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin)
```
