### ISSUE TITLE
Release 2.4.2

### ISSUE THREAD

**Issue by frol** [gmr/helper#9]
"Allow for 'root' section in logging config" - this is a quite important fix, and I struggled a couple of hours trying to understand what is going on before I finally noticed that I use 2.4.1!

**Comment by frol** [comment]
@gmr Please, make a release.

**Comment by gmr** [comment]
I am working on 3.0 which cleans up configuration a fair amount and allows for some interesting configuration loading features. I'm hoping to have this finished up next week as it's a dependency for another project I am working on at work.

**Comment by gmr** [comment]
Sorry, 2.4.2 is released and 3 was put on hold :|
